[package]
name = "ovi"
version = "0.1.0"
authors = ["Nathaniel J. Smith <njs@pobox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
serde = { version = "1.0.126", features = ["derive"] }
pep440 = "0.1.1"
ureq = { version = "2.1.1", features = ["json", "rustls-native-certs", "cookies"] }
zip = "0.5.13"
serde_json = "1.0.64"
url = { version = "2.2.2", features = ["serde"] }
nom = "6.1.2"
nom-supreme = "0.4.3"

[dev-dependencies]
indoc = "1.0.3"
